.github/workflows/deploy-production.yml

Add Eindhoven to production

---

src/app/components/offer/offer.component.ts
src/app/models/logging-event.enum.ts
src/app/referral/referral.page.ts
src/app/services/logging.service.ts

Track Offer Names (when available) + other metrics tweaks

---

.github/workflows/deploy-staging-ukr.yml

Add Opvang staging sheet

---

.github/workflows/upgrade-dependencies.yml

To be able to run default configured CI/CD workflows

Change to use Issue instead of PR

---

.github/workflows/codeql-analysis.yml
.github/workflows/deploy-production-ukr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging-ukr.yml
.github/workflows/deploy-staging.yml
CHANGELOG.md
README.md
package.json
src/app/models/category.model.ts
src/app/models/offer.model.ts
src/app/models/qa-set.model.ts
src/app/models/sub-category.model.ts
src/app/services/spreadsheet.service.ts

Use #tagged columns instead of hard-coded order/position in all sheets

---

README.md
src/app/models/referral-page-data.ts
src/app/referral/referral.page.html
src/app/referral/referral.page.ts
src/app/services/spreadsheet.service.ts
src/global.scss

fix: Sort Highlights by most-recent first, no dates last

---

.github/workflows/deploy-production-faq.yml
.github/workflows/deploy-production-ukr.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging-faq.yml
.github/workflows/deploy-staging.yml

Reverts rodekruis/helpful-information#526

Revert "Tweak URLs of FAQ-environment(s) + fix multi-line syntax in workflows"

---

src/app/components/header/header.component.html
src/app/components/header/header.component.scss

fix: refactor Ionicon out of back-button

---

.github/workflows/deploy-production-ukr.yml

Change UKR into redirect to FAQ

---

.github/workflows/deploy-production-ukr.yml

Fix: Set redirect to permanent

---

.github/workflows/deploy-production-ukr.yml

Create specific redirects for UKR→FAQ

---

.github/workflows/deploy-production-ukr.yml

Try to make old service-workers self-destruct

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Remove COVID-19 related region/sheet(s) + update main-page text

---

data/test-sheet-id-1/values/Offers.json
src/app/components/offer/offer.component.html
src/app/components/offer/offer.component.scss
src/app/models/offer.model.ts
src/app/pages/category/category.page.html
src/app/pages/sub-category/sub-category.page.html
src/app/services/spreadsheet.service.ts
src/global.scss

feat: Remove covid-related/specific columns/fields

---

src/app/pages/category/category.page.ts
src/app/pages/highlights/highlights.page.ts
src/app/pages/offer/offer.page.ts
src/app/pages/region/region.page.ts
src/app/pages/search/search.page.ts
src/app/pages/sub-category/sub-category.page.ts
src/app/referral/referral.page.ts
src/app/services/page-meta.service.ts

Add a link-element with the canonical URL to every page

---

docs/Guide-How_to_set_up_an_instance.md

Create Guide: "How to set up an instance"

---

src/app/components/category-link/cateogry-link.component.html
src/app/components/offer-link/offer-link.component.html
src/app/components/offer/offer.component.html
src/app/pages/category/category.page.html
src/app/pages/highlights/highlights.page.html
src/app/pages/search/search.page.html
src/app/pages/sub-category/sub-category.page.html
src/app/referral/referral.page.html
src/global.scss

Adjust typography

---

.github/workflows/deploy-production-ocw.yml

Create new OCW instance deploy workflow

---

README.md
data/test-sheet-id-1/values/Offers.json
data/test-sheet-id-1/values/Referral Page.json
src/app/components/last-updated-time/last-updated-time.component.html
src/app/components/last-updated-time/last-updated-time.component.ts
src/app/components/offer/offer.component.html
src/app/components/offer/offer.component.ts
src/app/mocks/offer.mock.ts
src/app/models/offer.model.ts
src/app/models/region-data.ts
src/app/pages/offer/offer.page.html
src/app/pages/offer/offer.page.spec.ts
src/app/pages/offer/offer.page.ts
src/app/services/spreadsheet.service.ts

Use config-sheet for translations of Offer section-labels

---

data/test-sheet-id-1/values/Referral Page.json
src/app/app.scss
src/app/components/header/header.component.scss
src/app/components/offer/offer.component.scss
src/app/components/search-input/search-input.component.scss
src/app/models/region-data.ts
src/app/pages/highlights/highlights.page.ts
src/app/pages/offer/offer.page.ts
src/app/pages/region/region.page.ts
src/app/pages/search/search.page.ts
src/app/referral/referral.page.html
src/app/referral/referral.page.ts
src/app/services/page-meta.service.ts
src/app/services/spreadsheet.service.ts
src/global.scss
src/index.html

Add LTR/RTL switching to use multiple locales/languages

---

src/app/components/header/header.component.html
src/global.scss

fix: Direction of 'back'-icon for RTL-mode

---

src/app/models/logging-event.enum.ts
src/app/services/spreadsheet.service.ts

Add error-logging/handling around fetching sheets

---

src/global.scss

feat: Adjust styles when using Google Translate (live)

---

docs/Guide-How_to_set_up_an_instance.md

docs: Simplify Set-up Guide by using optimised template

---

.github/workflows/deploy-production-ocw.yml

instance: Add V2 sheets for OCW

---

.github/workflows/deploy-production.yml

instance: Change opening hours

---

.env.example
CHANGELOG.md
data/test-sheet-id-1/values/Referral Page.json
src/app/components/q-a-set/q-a-set.component.ts
src/app/components/search-input/search-input.component.css
src/app/components/search-input/search-input.component.html
src/app/components/search-input/search-input.component.ts
src/app/models/logging-event.enum.ts
src/app/models/region-data.ts
src/app/pages/search/search.page.html
src/app/pages/search/search.page.ts
src/app/services/offers.service.ts
src/app/services/spreadsheet.service.ts
src/environments/environment.prod.ts.template.js
src/environments/environment.test.ts
src/environments/environment.ts

feat: Add Search-via-API feature

---

CHANGELOG.md
src/app/components/feedback-link/feedback-link.component.html

feat: Always show "Share feedback CTA" after initial response
